version: 2.1
orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@1.0.6
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test:coveralls
          name: Run tests
      - coveralls/upload
      - run:
          command: npm run eslint
          name: Run eslint
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  deploy: # this can be any name you choose
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/app
      - heroku/deploy-via-git:
          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: master # only deploy when on main
