version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: eslint 'src/**'
      - run: npm run test:coveralls
